Add session naming options, type definitions
LambdaTest/wdio-lambdatest-service pull request #48
Opened 2023-01-12 10:21 UTC by SCG82

Adds session naming options from https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-browserstack-service/src/service.ts.

2023-01-12 18:21 UTC, SCG82 commented
ready for review

2023-04-26 10:40 UTC, Shivanshu-lambdatest commented
Thanks @SCG82 for the PR, it looks Good to me. There are some conflicts here. We will publish your changes with a new PR from our side and close this one.

2023-04-26 10:43 UTC, Shivanshu-lambdatest requested changes

2023-04-26 10:43 UTC, Shivanshu-lambdatest commented on src/service.js
> +      return this._update(this._browser.sessionId, failures);
In certain cases if some unhandled exception occurs, after test hook is skipped and this._failures will not be set & in those cases correct status won't be reflected on the LT dashboard.

2023-05-27 10:21 UTC, closed without merging